### ISSUE TITLE
Quantum Chess : Swap operation iteration

### ISSUE THREAD

**Issue by buttercutter** [quantumlib/unitary#58]
1. Are there any specific reasons why both `i_SWAP` and `i_SQRT_SWAP` gates are needed ?  Note: I found one paper on this [Quantum Chess: Developing a Mathematical Framework and Design Methodology for Creating Quantum Games](https://arxiv.org/pdf/1906.05836.pdf#page=5), but I am a bit confused.

2. Why use `i_SWAP` instead of just `SWAP` ?  

3. It seems like that the swapping is only used for restoring graph correctness if you trace the [swapping code](https://github.com/quantumlib/unitary/blob/e93c137e0104fb2cee3de117644d30989839222d/unitary/quantum_chess/swap_updater.py#L151) to its original function caller ?  I noticed that swapping is needed for both split slide and merge slide operations ?

![image](https://user-images.githubusercontent.com/3324659/179368339-90702bc6-c61a-4c2e-80d7-06d1cd951219.png)

**Comment by cantwellc** [comment]
You can certainly use swap instead of iswap. There were a couple of reasons for the choice.

1. iswap is a natural unitary for some superconducting qubits.
2. iswap introduces a bit more phase complexity into the game.

The first reason was the main driving factor. The game did use swap before we began the work to run on hardware. In that process I had to change a lot of the rules and math, so in the process I switched to iswap. I hoped it would lead to smaller circuits in some cases.
